# Generated by Django 5.0.1 on 2024-08-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0003_alter_comment_music_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='musics',
            name='slug',
            field=models.SlugField(blank=True, max_length=30),
        ),
    ]
