# Generated by Django 5.0.1 on 2024-08-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0004_musics_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musics',
            name='slug',
            field=models.SlugField(max_length=30),
        ),
    ]
