# Generated by Django 5.0.1 on 2024-08-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0007_alter_musics_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musics',
            name='slug',
            field=models.SlugField(blank=True, max_length=30, unique=True),
        ),
    ]
