# Generated by Django 5.0.1 on 2024-08-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0009_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='slug',
            field=models.SlugField(blank=True, default='', unique=True),
        ),
    ]
