# Generated by Django 5.0.1 on 2024-08-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musics', '0010_alter_test_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
