# Generated by Django 5.0.1 on 2024-04-12 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_useraccount_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='date_of_birth',
        ),
    ]
